# Generated by Django 4.1.7 on 2023-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_sounds', '0002_alter_sound_name_alter_sound_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='audioname',
            field=models.FileField(default=True, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sound',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
