# Generated by Django 4.1.7 on 2023-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_sounds', '0003_sound_audioname_alter_sound_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
